services:
  postgres:
    image: postgres:18

    container_name: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: development

    ports:
      - "127.0.0.1:5432:5432"

    volumes:
      - ./postgresql_data:/var/lib/postgresql:z

    restart: unless-stopped